#!/bin/sh

update-mime-database /usr/share/mime

echo "application/webinos-widget=webinosBrowser.desktop" >> /usr/share/applications/defaults.list

for user in /home/*
do
	if [ "${user}" == "/home/lost" ]
	then
		continue
	fi
	if [ -d "${user}/.webinos" ];
	then
		echo ".webinos exists"
	else
		mkdir ${user}/.webinos
		chmod og+w ${user}/.webinos
		mkdir ${user}/.webinos/wrt
		chmod og+w ${user}/.webinos/wrt
                mkdir ${user}/.webinos/wrt/widgetStore
                chmod og+w ${user}/.webinos/wrt/widgetStore
                cp -R /usr/local/share/webinos/bin/preinstalled/* ${user}/.webinos/wrt/widgetStore
	fi	
	echo "{
\"nodePath\": \"/usr/local/share/webinos/bin\",
\"workingDirectoryPath\": \"/usr/local/share/webinos/webinos-pzp\",
\"nodeArgs\": \"webinos_pzp.js --widgetServer\",
\"instance\": 0
}" >> ${user}/.webinos/wrt/webinos_pzp.json 

# disable daemon for time being as there is currently no UI for it.
if false; then
echo "[Desktop Entry]
Name=Webinos PZP
Comment=Startup for the webinos PZP.
Exec=/usr/local/share/webinos/bin/wrt/webinosDaemon
Terminal=false
Type=Application
StartupNotify=true
Icon=utilities-system-monitor
Categories=GNOME;System;
X-GNOME-Autostart-enabled=true" >> ${user}/.config/autostart/webinos-PZP.desktop
fi
done

